// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: podcasts.sql

package model

import (
	"context"
	"database/sql"
)

const createPodcast = `-- name: CreatePodcast :one
INSERT INTO podcasts(
    link,
    title,
    description
) VALUES (?, ?, ?) RETURNING id, link, title, description
`

type CreatePodcastParams struct {
	Link        string
	Title       string
	Description sql.NullString
}

func (q *Queries) CreatePodcast(ctx context.Context, arg CreatePodcastParams) (Podcast, error) {
	row := q.db.QueryRowContext(ctx, createPodcast, arg.Link, arg.Title, arg.Description)
	var i Podcast
	err := row.Scan(
		&i.ID,
		&i.Link,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const listEpisodes = `-- name: ListEpisodes :many
SELECT id, uuid, feed_id, url, title, description, pub_date, file_size, duration, audio_content FROM episodes
`

func (q *Queries) ListEpisodes(ctx context.Context) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.FeedID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.PubDate,
			&i.FileSize,
			&i.Duration,
			&i.AudioContent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPodcasts = `-- name: ListPodcasts :many
SELECT id, link, title, description FROM podcasts
`

func (q *Queries) ListPodcasts(ctx context.Context) ([]Podcast, error) {
	rows, err := q.db.QueryContext(ctx, listPodcasts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Podcast
	for rows.Next() {
		var i Podcast
		if err := rows.Scan(
			&i.ID,
			&i.Link,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
