// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: podcasts_feeds.sql

package model

import (
	"context"
)

const createPodcastFeed = `-- name: CreatePodcastFeed :one
INSERT INTO podcast_feed(
    podcast_id,
    feed_id
) VALUES (?, ?) RETURNING podcast_id, feed_id
`

type CreatePodcastFeedParams struct {
	PodcastID int64
	FeedID    int64
}

func (q *Queries) CreatePodcastFeed(ctx context.Context, arg CreatePodcastFeedParams) (PodcastFeed, error) {
	row := q.db.QueryRowContext(ctx, createPodcastFeed, arg.PodcastID, arg.FeedID)
	var i PodcastFeed
	err := row.Scan(&i.PodcastID, &i.FeedID)
	return i, err
}
